name: Bump, Tag, Publish, and Deploy
# The purpose of the workflow is to:
#  1. Bump the version number and tag the release
#  3. Build docker image and publish to GCR
#  4. Trigger deployment to the an azure sandbox dev environment
#
# When run on merge to dev, it tags and bumps the patch version by default. You can
# bump other parts of the version by putting #major, #minor, or #patch in your commit
# message.
#
# The workflow relies on github secrets:
# - GCR_PUBLISH_EMAIL - email for publishing the docker to GCR
# - GCR_PUBLISH_KEY   - key for publishing the docker to GCR
# - BROADBOT_TOKEN - the broadbot token, so we can avoid two reviewer rule on GHA operations
on:
  push:
    branches:
    - main
    paths-ignore:
    - 'README.md'
    - '.github/**'
    - 'local-dev/**'
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'README.md'
  workflow_dispatch:
    inputs:
      bump:
        description: 'Part of the version to bump: major, minor, patch'
        required: false
        default: 'patch'
      branch:
        description: 'Branch to run the workflow on'
        required: false
        default: 'main'
env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  GOOGLE_PROJECT: terra-kernel-k8s
  GKE_CLUSTER: terra-kernel-k8s
jobs:
  tag-publish-job:
    runs-on: ubuntu-latest
    steps:
    - name: Set part of semantic version to bump
      id: semver
      run: |
        SEMVER_PART=""
        CHECKOUT_BRANCH="$GITHUB_REF"
        if ${{github.event_name == 'push' }}; then
          SEMVER_PART="patch"
        elif ${{github.event_name == 'workflow_dispatch' }}; then
          SEMVER_PART=${{ github.event.inputs.bump }}
          CHECKOUT_BRANCH=${{ github.event.inputs.branch }}
        fi
        echo ::set-output name=semver-part::$SEMVER_PART
        echo ::set-output name=checkout-branch::$CHECKOUT_BRANCH
    - name: Checkout current code
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.controls.outputs.checkout-branch }}
        token: ${{ secrets.BROADBOT_TOKEN }}
    - name: Bump the tag to a new version
      uses: databiosphere/github-actions/actions/bumper@bumper-0.0.3
      id: tag
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
        RELEASE_BRANCHES: main
    - name: Set up AdoptOpenJDK
      uses: joschi/setup-jdk@v2
      with:
        java-version: 11
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
        restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Auth to GCR
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_email: ${{ secrets.GCR_PUBLISH_EMAIL }}
        service_account_key: ${{ secrets.GCR_PUBLISH_KEY }}
    - name: Explicitly auth Docker for GCR
      run: gcloud auth configure-docker --quiet
    - name: Construct docker image name and tag
      id: image-name
      run: |
        DOCKER_TAG=${{ steps.tag.outputs.tag }}
        echo ::set-output name=name::gcr.io/${GOOGLE_PROJECT}/${SERVICE_NAME}:${DOCKER_TAG}
    - name: Build image locally with jib
      run: "./gradlew jibDockerBuild --image=${{ steps.image-name.outputs.name }} -Djib.console=plain"
    - name: Run Trivy vulnerability scanner
      # Link to the github location of the action https://github.com/broadinstitute/dsp-appsec-trivy-action
      uses: broadinstitute/dsp-appsec-trivy-action@v1
      with:
        image: ${{ steps.image-name.outputs.name }}
    - name: Push GCR image
      run: "docker push ${{ steps.image-name.outputs.name }}"
    - name: Deploy to Terra Dev environment
      if: github.event_name == 'push'
      uses: broadinstitute/repository-dispatch@master
      with:
        token: ${{ secrets.BROADBOT_TOKEN }}
        repository: broadinstitute/terra-helmfile
        event-type: update-service
        client-payload: '{"service": "azurepoc", "version": "${{ steps.tag.outputs.tag }}", "dev_only": false}'
    - name: Notify Slack
      # only notify for develop branch build
      if: github.event_name == 'push'
      uses: broadinstitute/action-slack@v3.8.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        status: ${{ job.status }}
        channel: "#ap-devops"
        fields: repo,commit,author,action,eventName,ref,workflow,job,took
